In [1]:
# general imports
import pandas as pd

# MMAI Examples

## Trial Summarization

### Read in data

In [2]:
trials_path = "data/scheduled__2025-09-04T230000+0000.trials_for_summarize.csv"
trials = pd.read_csv(trials_path)

### Convert column names to those expected by the function.
- `trial_id`
- `trial_title`
- `brief_summary`
- `eligibility_criteria`

In [3]:
trials.rename(columns = {'title':'trial_title', 'nct_id':'trial_id'},inplace= True)

### Run `summarize_trials` function on 10 trials

*Note: You can turn debug mode on to add intermediate summarization outputs to the dataframe. Example below*
```python
from mmai import load_preset
config = load_preset("default")
config.debug_mode = True
df, metadata = summarize_trials(trials, config=config, return_metadata=True)
```

In [4]:
# subset to 10 trials
trials = trials.iloc[0:10,]

# import and run function on trial data
from mmai.trials import summarize_trials
trial_results, metadata = summarize_trials(trials, return_metadata=True)

/home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

INFO 01-21 19:31:13 [utils.py:263] non-default args: {'max_model_len': 15000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 01-21 19:31:14 [model.py:530] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:01<00:00, 11.90it/s]

INFO 01-21 19:31:15 [model.py:1545] Using max model len 15000

2026-01-21 19:31:17,931	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

INFO 01-21 19:31:17 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 01-21 19:31:17 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.
INFO 01-21 19:31:17 [vllm.py:630] Asynchronous scheduling is enabled.
INFO 01-21 19:31:17 [vllm.py:637] Disabling NCCL for DP synchronization when using async scheduling.
(EngineCore_DP0 pid=13821) INFO 01-21 19:31:19 [core.py:97] Initializing a V1 LLM engine (v0.14.0) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=15000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=13821) INFO 01-21 19:31:20 [parallel_state.py:1214] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:53801 backend=nccl
(EngineCore_DP0 pid=13821) INFO 01-21 19:31:20 [parallel_state.py:1425] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=13821) INFO 01-21 19:31:21 [gpu_model_runner.py:3808] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=13821) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=13821) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=13821)   warnings.warn(

(EngineCore_DP0 pid=13821) INFO 01-21 19:31:21 [cuda.py:351] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=13821) INFO 01-21 19:31:22 [mxfp4.py:162] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:15<03:40, 15.74s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:29<03:11, 14.74s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:45<03:02, 15.21s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:59<02:42, 14.74s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [01:13<02:24, 14.42s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [01:27<02:08, 14.22s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [01:43<01:57, 14.73s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [01:57<01:41, 14.51s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [02:11<01:26, 14.41s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [02:25<01:11, 14.29s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [02:41<00:58, 14.74s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [02:56<00:45, 15.05s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [03:12<00:30, 15.27s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [03:28<00:15, 15.42s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [03:42<00:00, 15.00s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [03:42<00:00, 14.83s/it]
(EngineCore_DP0 pid=13821)

(EngineCore_DP0 pid=13821) INFO 01-21 19:35:05 [default_loader.py:291] Loading weights took 222.48 seconds
(EngineCore_DP0 pid=13821) WARNING 01-21 19:35:05 [marlin_utils_fp4.py:333] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:09 [gpu_model_runner.py:3905] Model loading took 65.97 GiB memory and 226.527022 seconds
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:18 [backends.py:644] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/aaa5864358/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:18 [backends.py:704] Dynamo bytecode transform time: 8.58 s
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:32 [backends.py:226] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 9.561 s
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:32 [monitor.py:34] torch.compile takes 18.14 s in total
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:33 [gpu_worker.py:358] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:34 [kv_cache_utils.py:1305] GPU KV cache size: 48,656 tokens
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:34 [kv_cache_utils.py:1310] Maximum concurrency for 15,000 tokens per request: 4.17x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.31it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:10<00:00,  3.22it/s]

(EngineCore_DP0 pid=13821) INFO 01-21 19:35:55 [gpu_model_runner.py:4856] Graph capturing finished in 21 secs, took 1.12 GiB
(EngineCore_DP0 pid=13821) INFO 01-21 19:35:55 [core.py:273] init engine (profile, create kv cache, warmup model) took 46.10 seconds
INFO 01-21 19:35:55 [llm.py:347] Supported tasks: ['generate']

Adding requests: 100%|██████████| 10/10 [00:00<00:00, 119.91it/s]
Processed prompts: 100%|██████████| 10/10 [00:38<00:00,  3.82s/it, est. speed input: 647.25 toks/s, output: 427.40 toks/s]
[2026-01-21 19:36:34] INFO __init__.py:92: Completed LLM summarization. Beginning postprocessing.
/home/sabrina/mmai-package/src/mmai/trials/postprocess.py:46: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  trials_with_summaries["boilerplate_text"].fillna(
[2026-01-21 19:36:34] INFO __init__.py:94: Postprocessing complete. Produced 24 rows.

### View results

In [5]:
trial_results.head()

,trial_id,clinical_space_number,clinical_space_summary,general_exclusion_criteria,space_trial_id
0,NCT03319901,1,Cancer type allowed: acute lymphoblastic leuke...,* Pregnant or breast‑feeding individuals \n* ...,NCT03319901-1
1,NCT03319901,2,Cancer type allowed: acute lymphoblastic leuke...,* Pregnant or breast‑feeding individuals \n* ...,NCT03319901-2
2,NCT03319901,3,Cancer type allowed: acute lymphoblastic leuke...,* Pregnant or breast‑feeding individuals \n* ...,NCT03319901-3
3,NCT03319901,4,Cancer type allowed: acute lymphoblastic leuke...,* Pregnant or breast‑feeding individuals \n* ...,NCT03319901-4
4,NCT04792489,1,Cancer type allowed: Diffuse large B‑cell lymp...,* History of infection with Human Immunodefici...,NCT04792489-1

Metadata contains a snapshot of the config used and metadata on the model used.

In [6]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 15000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 10000,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate exclusions:'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7000,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate:',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'trial_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

## Patient summarization

In [8]:
notes_path = "data/2026_01_16_dummy_notes.csv"
notes = pd.read_csv(notes_path)
notes.head()

,DFCI_MRN,EVENT_DATE,RPT_TEXT,NOTE_SOURCE,LAST_MOD,PROVIDER_TYPE,RPT_STATUS,ENCOUNTER_TYPE_DESC,PROVIDER_DEPT,PROC_DESC
0,-1,6/20/25,**Imaging Report**\n\n---\n\n**Patient:** Mich...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
1,-1,6/25/25,**Oncology Progress Note – Follow‑Up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
2,-2,6/19/25,**Imaging Report**\n\n**Patient:** Daniel O’Co...,Imaging,6/25/25,PROVIDER_TYPE_NM,NOTE_STATUS_DESCR,ENCOUNTER_TYPE_DESCR,NaN,NaN
3,-2,6/20/25,**Oncology Progress Note**\n\n**Patient:** Dan...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN
4,-2,6/25/25,**Oncology Progress Note – Follow‑up Visit**\n...,progress_notesbase,6/25/25,Physician,Signed,Office Visit,NaN,NaN

Convert column names to those expected by the function.
- `patient_id`
- `note_text`
- `note_type`
- `note_date`

In [9]:
notes.rename(columns = {'DFCI_MRN': 'patient_id', 'RPT_TEXT':'note_text', 'NOTE_SOURCE':'note_type', 'EVENT_DATE':'note_date'}, inplace = True)

**Run patient summarization.**

*Note: You can turn debug mode on to add intermediate summarization outputs to the dataframe. Example below*
```python
from mmai import load_preset
config = load_preset("default")
config.debug_mode = True
df, metadata = summarize_patients(notes, config=config, return_metadata=True)
```

In [ ]:
from mmai.patients import summarize_patients
summaries, metadata = summarize_patients(notes, return_metadata=True)

[2026-01-26 19:22:46] INFO __init__.py:87: Extracting relevant patient sentences from 35 notes.
/home/sabrina/mmai-package/src/mmai/patients/tagging.py:184: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["note_date"] = pd.to_datetime(df["note_date"])
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
[2026-01-26 19:22:55] INFO __init__.py:92: Extracted relevant text for 12 patients.

INFO 01-26 19:22:56 [utils.py:263] non-default args: {'max_model_len': 120000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 01-26 19:22:56 [model.py:530] Resolved architecture: GptOssForCausalLM

Parse safetensors files: 100%|██████████| 15/15 [00:02<00:00,  6.41it/s]

INFO 01-26 19:22:59 [model.py:1545] Using max model len 120000
INFO 01-26 19:22:59 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 01-26 19:22:59 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.

(EngineCore_DP0 pid=17644) INFO 01-26 19:23:06 [core.py:97] Initializing a V1 LLM engine (v0.14.1) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=120000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:06 [parallel_state.py:1214] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:42373 backend=nccl
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:07 [parallel_state.py:1425] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:07 [gpu_model_runner.py:3808] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=17644) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=17644) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=17644)   warnings.warn(

(EngineCore_DP0 pid=17644) INFO 01-26 19:23:08 [cuda.py:351] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:08 [mxfp4.py:162] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:17,  1.26s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:15,  1.22s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:14,  1.25s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:13,  1.22s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:06<00:11,  1.19s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.17s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.21s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:08,  1.20s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:07,  1.19s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:11<00:05,  1.18s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:04,  1.22s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:14<00:03,  1.25s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:15<00:02,  1.26s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:17<00:01,  1.28s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.25s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.23s/it]
(EngineCore_DP0 pid=17644)

(EngineCore_DP0 pid=17644) INFO 01-26 19:23:27 [default_loader.py:291] Loading weights took 18.46 seconds
(EngineCore_DP0 pid=17644) WARNING 01-26 19:23:27 [marlin_utils_fp4.py:333] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:31 [gpu_model_runner.py:3905] Model loading took 65.97 GiB memory and 22.425518 seconds
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:40 [backends.py:644] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/cbf5f76226/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:40 [backends.py:704] Dynamo bytecode transform time: 9.12 s
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:57 [backends.py:226] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 8.991 s
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:57 [monitor.py:34] torch.compile takes 18.11 s in total
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:58 [gpu_worker.py:358] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:58 [kv_cache_utils.py:1305] GPU KV cache size: 48,656 tokens
(EngineCore_DP0 pid=17644) INFO 01-26 19:23:58 [kv_cache_utils.py:1310] Maximum concurrency for 120,000 tokens per request: 0.76x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.62it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  9.64it/s]

(EngineCore_DP0 pid=17644) INFO 01-26 19:24:12 [gpu_model_runner.py:4856] Graph capturing finished in 13 secs, took 1.12 GiB
(EngineCore_DP0 pid=17644) INFO 01-26 19:24:12 [core.py:273] init engine (profile, create kv cache, warmup model) took 41.05 seconds
(EngineCore_DP0 pid=17644) INFO 01-26 19:24:14 [vllm.py:630] Asynchronous scheduling is enabled.
INFO 01-26 19:24:14 [llm.py:347] Supported tasks: ['generate']

Adding requests: 100%|██████████| 12/12 [00:00<00:00, 169.31it/s]
Processed prompts: 100%|██████████| 12/12 [00:24<00:00,  2.03s/it, est. speed input: 1056.66 toks/s, output: 558.56 toks/s]
[rank0]:[W126 19:24:38.802082537 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2026-01-26 19:24:39] INFO __init__.py:97: Patient summarization complete. Produced 12 rows.

In [14]:
summaries.head()

,patient_id,cancer_history_summary,general_exclusion_criteria_evidence
0,-12,Cancer type: Osteosarcoma \nHistology: High‑g...,"No evidence of uncontrolled brain metastases, ..."
1,-11,Cancer type: Cutaneous malignant melanoma (lef...,No evidence of common boilerplate exclusion cr...
2,-10,Cancer type: Ovarian cancer \nHistology: Low‑...,"No evidence of uncontrolled brain metastases, ..."
3,-9,Cancer type: T‑cell lymphoblastic lymphoma (me...,• Liver dysfunction – Grade 3 transaminitis (A...
4,-8,Cancer type: High‑grade serous ovarian carcino...,"No evidence of uncontrolled brain metastases, ..."

Metadata contains a snapshot of the config used and metadata on the models used.

In [15]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 15000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 10000,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate exclusions:'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7000,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate:',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'patient_tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
   'model_sha': 'f776e1156bd881fb3a976e05c42442a147ddb324',
   'created_at': '2025-09-16T15:06:51+00:00',
   'last_modified': '2025-12-09T20:44:46+00:00'},
  'patient_summarizer': {'model_name': 'openai/gpt-oss-120b',
   'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
   'created_at': '2025-08-04T22:33:06+00:00',
   'last_modified': '2025-08-26T17:25:03+00:00'}}}

Patient summarization is made of two main steps, extraction of relevant sentences and subsequent summarization of those sentences. Below we show how you can run those two steps separately rather than together via `summarize_patients(...)`

### (1/2) Extract relevant sentences

In [16]:
# import and run function on synthetic patient notes
from mmai.patients.tagging import extract_relevant_sentences
relevant_text, metadata = extract_relevant_sentences(notes)

/home/sabrina/mmai-package/src/mmai/patients/tagging.py:184: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["note_date"] = pd.to_datetime(df["note_date"])
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda
Device set to use cuda

#### View results

In [17]:
relevant_text.head()

   patient_id                                  patient_long_text
0         -12  2025-06-22 progress_notesbase **Oncology Progr...
1         -11  2025-06-22 progress_notesbase **Oncology Progr...
2         -10  2025-06-22 Imaging **PATIENT:** Susan Patel **...
3          -9  2025-06-20 Imaging **Imaging Report – Positron...
4          -8  2025-06-20 progress_notesbase **Oncology Follo...

Metadata contains a snapshot of the config used and metadata on the model used.

In [18]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 15000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 10000,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate exclusions:'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7000,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate:',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
  'model_sha': 'f776e1156bd881fb3a976e05c42442a147ddb324',
  'created_at': '2025-09-16T15:06:51+00:00',
  'last_modified': '2025-12-09T20:44:46+00:00'}}

### (2/2) Summarize relevant sentences

In [19]:
from mmai.patients.summarize import summarize_from_relevant_sentences
summaries, metadata = summarize_from_relevant_sentences(relevant_text)

INFO 01-26 19:29:21 [utils.py:263] non-default args: {'max_model_len': 120000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 01-26 19:29:21 [model.py:530] Resolved architecture: GptOssForCausalLM

Parse safetensors files:  33%|███▎      | 5/15 [00:02<00:04,  2.28it/s]

ERROR 01-26 19:29:24 [repo_utils.py:65] Error retrieving safetensors: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 2a9e793b-bdbc-4f10-95c3-90330c606065)'), retrying 1 of 2

Parse safetensors files: 100%|██████████| 15/15 [00:02<00:00,  7.36it/s]

INFO 01-26 19:29:28 [model.py:1545] Using max model len 120000
INFO 01-26 19:29:28 [scheduler.py:229] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 01-26 19:29:28 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.

(EngineCore_DP0 pid=19682) INFO 01-26 19:29:35 [core.py:97] Initializing a V1 LLM engine (v0.14.1) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=120000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=19682) INFO 01-26 19:29:36 [parallel_state.py:1214] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:49815 backend=nccl
(EngineCore_DP0 pid=19682) INFO 01-26 19:29:36 [parallel_state.py:1425] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=19682) INFO 01-26 19:29:36 [gpu_model_runner.py:3808] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=19682) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=19682) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=19682)   warnings.warn(

(EngineCore_DP0 pid=19682) INFO 01-26 19:29:37 [cuda.py:351] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=19682) INFO 01-26 19:29:37 [mxfp4.py:162] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:17,  1.24s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:15,  1.19s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:14,  1.22s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:04<00:13,  1.19s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:05<00:11,  1.17s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.15s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:09,  1.19s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:09<00:08,  1.18s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:10<00:07,  1.17s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:11<00:05,  1.16s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:04,  1.20s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:14<00:03,  1.22s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:15<00:02,  1.24s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:16<00:01,  1.25s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.22s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:18<00:00,  1.20s/it]
(EngineCore_DP0 pid=19682)

(EngineCore_DP0 pid=19682) INFO 01-26 19:29:56 [default_loader.py:291] Loading weights took 18.07 seconds
(EngineCore_DP0 pid=19682) WARNING 01-26 19:29:56 [marlin_utils_fp4.py:333] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=19682) INFO 01-26 19:29:59 [gpu_model_runner.py:3905] Model loading took 65.97 GiB memory and 21.921275 seconds
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:09 [backends.py:644] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/cbf5f76226/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:09 [backends.py:704] Dynamo bytecode transform time: 9.07 s
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:25 [backends.py:226] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 8.995 s
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:25 [monitor.py:34] torch.compile takes 18.07 s in total
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:27 [gpu_worker.py:358] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:27 [kv_cache_utils.py:1305] GPU KV cache size: 48,656 tokens
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:27 [kv_cache_utils.py:1310] Maximum concurrency for 120,000 tokens per request: 0.76x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.70it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:03<00:00,  9.80it/s]

(EngineCore_DP0 pid=19682) INFO 01-26 19:30:40 [gpu_model_runner.py:4856] Graph capturing finished in 13 secs, took 1.12 GiB
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:40 [core.py:273] init engine (profile, create kv cache, warmup model) took 40.80 seconds
(EngineCore_DP0 pid=19682) INFO 01-26 19:30:42 [vllm.py:630] Asynchronous scheduling is enabled.
INFO 01-26 19:30:42 [llm.py:347] Supported tasks: ['generate']

Adding requests: 100%|██████████| 12/12 [00:00<00:00, 170.42it/s]
Processed prompts: 100%|██████████| 12/12 [00:27<00:00,  2.28s/it, est. speed input: 938.60 toks/s, output: 522.64 toks/s]
[rank0]:[W126 19:31:10.366242042 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

#### View results

In [20]:
summaries.head()

,patient_id,cancer_history_summary,general_exclusion_criteria_evidence
0,-12,Cancer type: Osteosarcoma (high‑grade conventi...,"No evidence of uncontrolled brain metastases, ..."
1,-11,Cancer type: Cutaneous malignant melanoma (lef...,- No evidence of untreated or symptomatic brai...
2,-10,Cancer type: Ovarian cancer \nHistology: Low‑...,- Cardiovascular: Examination on 23 Jun 2025 n...
3,-9,Cancer type: T‑cell lymphoblastic lymphoma (me...,• Liver dysfunction – Transaminitis noted on 6...
4,-8,Cancer type: Ovarian cancer \nHistology: High...,"No evidence of uncontrolled brain metastases, ..."

Metadata contains a snapshot of the config used and metadata on the model used.

In [21]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'backend': 'local',
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'trial': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 15000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 10000,
    'repetition_penalty': 1.3},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate exclusions:'},
  'patient': {'model_name': 'openai/gpt-oss-120b',
   'max_model_len': 120000,
   'tensor_parallel_size': 1,
   'gpu_memory_utilization': 0.9,
   'sampling_params': {'temperature': 0.0,
    'top_k': 1,
    'max_tokens': 7000,
    'repetition_penalty': 1.2},
   'prompt_files': {'primer': 'patient.user.primer.txt',
    'question': 'patient.user.question.txt'},
   'reasoning_marker': 'assistantfinal',
   'boilerplate_marker': 'Boilerplate:',
   'text_token_threshold': 115000,
   'tagger': {'model_name': 'ksg-dfci/TinyBertOncoTagger-1225',
    'device': 'cuda',
    'positive_tag_cutoff': 0.1,
    'negative_tag_cutoff': 0.9}}},
 'model_metadata': {'model_name': 'openai/gpt-oss-120b',
  'model_sha': 'b5c939de8f754692c1647ca79fbf85e8c1e70f8a',
  'created_at': '2025-08-04T22:33:06+00:00',
  'last_modified': '2025-08-26T17:25:03+00:00'}}

# MMAI QC

## Trial summarization

In [2]:
trials_path = "data/scheduled__2025-09-04T230000+0000.trials_for_summarize.csv"
trials = pd.read_csv(trials_path)

trials.rename(columns = {'title':'trial_title', 'nct_id':'trial_id'},inplace= True)

In [3]:
from mmai import load_preset
# import and run function on trial data
from mmai.trials import summarize_trials
config = load_preset("default")
config.debug_mode = True
trial_results, metadata = summarize_trials(trials.iloc[0:200,], config = config, return_metadata=True)

/home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

INFO 01-30 20:58:51 [utils.py:261] non-default args: {'max_model_len': 10000, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}
INFO 01-30 20:58:52 [model.py:541] Resolved architecture: GptOssForCausalLM

Parse safetensors files:  47%|████▋     | 7/15 [00:33<00:38,  4.75s/it]

ERROR 01-30 20:59:25 [repo_utils.py:47] Error retrieving safetensors: ('Connection broken: IncompleteRead(0 bytes read, 100001 more expected)', IncompleteRead(0 bytes read, 100001 more expected)), retrying 1 of 2

Parse safetensors files:  60%|██████    | 9/15 [00:23<00:15,  2.59s/it]

ERROR 01-30 20:59:51 [repo_utils.py:45] Error retrieving safetensors: ('Connection broken: IncompleteRead(0 bytes read, 100001 more expected)', IncompleteRead(0 bytes read, 100001 more expected))
INFO 01-30 20:59:51 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 01-30 20:59:51 [model.py:1561] Using max model len 10000

2026-01-30 20:59:53,213	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.

INFO 01-30 20:59:53 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 01-30 20:59:53 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.
INFO 01-30 20:59:53 [vllm.py:624] Asynchronous scheduling is enabled.
(EngineCore_DP0 pid=55448) INFO 01-30 20:59:55 [core.py:96] Initializing a V1 LLM engine (v0.15.0) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=10000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None}
(EngineCore_DP0 pid=55448) INFO 01-30 20:59:55 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.4:35009 backend=nccl
(EngineCore_DP0 pid=55448) INFO 01-30 20:59:55 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=55448) INFO 01-30 20:59:56 [gpu_model_runner.py:4021] Starting to load model openai/gpt-oss-120b...

(EngineCore_DP0 pid=55448) /home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tvm_ffi/_optional_torch_c_dlpack.py:174: UserWarning: Failed to JIT torch c dlpack extension, EnvTensorAllocator will not be enabled.
(EngineCore_DP0 pid=55448) We recommend installing via `pip install torch-c-dlpack-ext`
(EngineCore_DP0 pid=55448)   warnings.warn(

(EngineCore_DP0 pid=55448) INFO 01-30 20:59:57 [cuda.py:364] Using TRITON_ATTN attention backend out of potential backends: ('TRITON_ATTN',)
(EngineCore_DP0 pid=55448) INFO 01-30 20:59:57 [mxfp4.py:161] Using Marlin backend

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:01<00:18,  1.32s/it]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:02<00:16,  1.25s/it]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:03<00:15,  1.30s/it]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:05<00:13,  1.26s/it]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:06<00:12,  1.24s/it]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:07<00:10,  1.22s/it]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:08<00:10,  1.26s/it]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:10<00:08,  1.24s/it]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:11<00:07,  1.24s/it]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:12<00:06,  1.23s/it]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:13<00:05,  1.26s/it]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:15<00:03,  1.30s/it]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:16<00:02,  1.32s/it]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:17<00:01,  1.33s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:19<00:00,  1.30s/it]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:19<00:00,  1.28s/it]
(EngineCore_DP0 pid=55448)

(EngineCore_DP0 pid=55448) INFO 01-30 21:00:17 [default_loader.py:291] Loading weights took 19.23 seconds
(EngineCore_DP0 pid=55448) WARNING 01-30 21:00:17 [marlin_utils_fp4.py:336] Your GPU does not have native support for FP4 computation but FP4 quantization is being used. Weight-only FP4 compression will be used leveraging the Marlin kernel. This may degrade performance for compute-heavy workloads.
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:22 [gpu_model_runner.py:4118] Model loading took 65.97 GiB memory and 23.674837 seconds
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:31 [backends.py:805] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/bdd604333b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:31 [backends.py:865] Dynamo bytecode transform time: 9.51 s
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:38 [backends.py:267] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 1.303 s
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:38 [monitor.py:34] torch.compile takes 10.81 s in total
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:39 [gpu_worker.py:356] Available KV cache memory: 3.34 GiB
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:39 [kv_cache_utils.py:1307] GPU KV cache size: 48,688 tokens
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:39 [kv_cache_utils.py:1312] Maximum concurrency for 10,000 tokens per request: 5.31x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.50it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:04<00:00,  8.38it/s]

(EngineCore_DP0 pid=55448) INFO 01-30 21:00:54 [gpu_model_runner.py:5051] Graph capturing finished in 15 secs, took 1.12 GiB
(EngineCore_DP0 pid=55448) INFO 01-30 21:00:54 [core.py:272] init engine (profile, create kv cache, warmup model) took 32.97 seconds
INFO 01-30 21:00:57 [llm.py:343] Supported tasks: ['generate']

Adding requests: 100%|██████████| 200/200 [00:01<00:00, 118.19it/s]
Processed prompts: 100%|██████████| 200/200 [07:34<00:00,  2.27s/it, est. speed input: 1075.74 toks/s, output: 819.18 toks/s]
[2026-01-30 21:08:34] INFO __init__.py:92: Completed LLM summarization. Beginning postprocessing.
[2026-01-30 21:08:34] INFO __init__.py:94: Postprocessing complete. Produced 621 rows.

In [5]:
from mmai.qc.trials import trial_qc_report
qc_df = trial_qc_report(trial_results, trial_inputs=trials.iloc[0:200,])
qc_df

,metric,value,percent,ids
0,trials_missing_summaries,2.0,1.0,"[NCT05941507, NCT06586515]"
1,spaces_per_trial_min,1.0,NaN,[]
2,spaces_per_trial_median,2.0,NaN,[]
3,spaces_per_trial_max,34.0,NaN,[]
4,trials_with_non_distinct_spaces,2.0,1.0,"[NCT05098132, NCT05259839]"
5,spaces_missing_keyword:Age,0.0,0.0,[]
6,spaces_missing_keyword:Sex,0.0,0.0,[]
7,spaces_missing_keyword:Cancer type allowed,0.0,0.0,[]
8,spaces_missing_keyword:Histology allowed,0.0,0.0,[]
9,spaces_missing_keyword:Cancer burden allowed,0.0,0.0,[]
10,spaces_missing_keyword:Prior treatment required,0.0,0.0,[]
11,spaces_missing_keyword:Prior treatment excluded,0.0,0.0,[]
12,spaces_missing_keyword:Biomarkers required,0.0,0.0,[]
13,spaces_missing_keyword:Biomarkers excluded,0.0,0.0,[]
14,trials_missing_boilerplate_exclusions,2.0,1.0,"[NCT04150497, NCT05407441]"
15,spaces_excessive_length,0.0,0.0,[]

In [12]:
# Example: inspect spaces with no boilerplate
missing_boilerplate_ids = qc_df.loc[
    qc_df["metric"] == "trials_missing_boilerplate_exclusions", "ids"
].iloc[0]
trial_results[trial_results["trial_id"].isin(missing_boilerplate_ids)].drop_duplicates(subset = ['trial_id'])

,trial_id,clinical_space_number,clinical_space_summary,general_exclusion_criteria,space_trial_id,trial_text,space_reasoning_and_output
322,NCT05407441,1,Age range allowed: ≥6 months to ≤21 years. Sex...,None,NCT05407441-1,TAZNI: A Phase I/II Combination Trial of Tazem...,analysisWe need parse inclusion criteria.\n\nT...
437,NCT04150497,1,Age range allowed: NA. Sex allowed: Both. Canc...,None,NCT04150497-1,Open Label Dose-escalation and Dose-expansion ...,analysisWe need parse inclusion/exclusion.\n\n...

In [15]:
trial_results[trial_results["trial_id"].isin(missing_boilerplate_ids)].drop_duplicates(subset = ['trial_id'])['space_reasoning_and_output'].values[0]

'analysisWe need parse inclusion criteria.\n\nTrial defines various strata:\n\nStratum A:\n - AT RT? Actually they call Stratum A: Atypical Teratoid Rhabdoid Tumor (ATRT); Other INI1- or SMARCA4-deficient primary CNS malignant tumours (with PI approval)\n\nSo that\'s central nervous system primaries.\n\nWithin Stratum A further sub-strata maybe A1/A2/A3 depending on pre/post?\n\nBut we just need create distinct trial spaces per cancer type/histology combos.\n\nCancer types mentioned:\n\n- Atypical teratoid/rhabdoid tumour (CNS)\n- Primary CNS malignant tumors that are INI1- or SMARCA4-deficient (other CNS).\n- Malignant rhabdoid tumor (extra-CNS?) Usually soft tissue/kidney?\n- Rhabdoid tumor of the kidney (renal)\n- Epithelioid sarcoma\n- Chordoma (poorly differentiated/de‑differentiated)\n- Other INI1- or SMARCA4-deficient malignant tumors (any location?)\n\nThus many possibilities. We should produce separate spaces for each specific cancer type/histology combo where specified. Also consider stratification into disease status groups (evaluability vs measurable vs none). But requirement about disease status varies across strata/subgroups (A1/B1 require evaluable disease; A2/B2 measurable disease; A3/B3 no disease).\n\nThese represent different trial arms perhaps requiring different disease statuses. So those constitute separate spaces too, though still same cancer type possibly combined with disease status condition.\n\nThe instruction says don\'t combine multiple cancer types/histologies in one space. Could group \'Other ...\' generic category as separate space.\n\nAlso need capture age >=6 months <=21 yrs inclusive.\n\nSex unspecified -> Both sexes (since pediatric overall). However some cancers might be gender neutral anyway.\n\nBiomarker required: deficiency/loss of INI1 (SMARCB1) or SMARCA4 via IHC/molecular. Must have either loss of INI1 or loss of SMARCA4. That seems essential for eligibility regardless of tumor type. Should state "Loss of INI1 (by IHC or biallelic SMARCB1 alteration) AND/OR Loss of SMARCA4 (by IHC or SMARCA4 alteration)" Need logical clarity: Patient must have deficiency in ONE OF THE TWO proteins. Not necessarily both. So it\'s "(loss of INI1) OR (loss of SMARCA4)." Provide accordingly.\n\nPrior treatment required/excluded: They must have completed planned upfront treatment for certain strata (pre recurrent?). That\'s complicated. There is mention of prior therapies being washed-out but ignore washouts. There\'s rule: Prior allogeneic SCT not permissible. Prior EZH2 inhibitor permitted only for relapsed/refractory (strata A2,B2) up to 1 yr else cannot have prior EZH2 inhibitor. Since our spaces likely differentiate between relapsed/refractory vs newly diagnosed/pre-recurrence. We\'ll incorporate prior EZH2 inhibitor usage restrictions.\n\nThey exclude prior PD-1/PD-L1/CTLA4 antibodies ever. So prior exposure to checkpoint inhibitors excluded entirely irrespective of timing. Include as prior treatment excluded.\n\nExclude prior solid organ transplant, prior myeloid malignancy, prior autologous/stem cells >42days needed but okay. Probably not needed as explicit exclusion.\n\nWe\'ll craft spaces focusing on key aspects: Age, Sex, Cancer Type/Histo, Biomarker (INi1 or SMARCA4 loss), Cancer Burden/Evaluability (Evaluable disease, Measurable disease, No residual disease), Prior treatment required (completion of standard frontline therapy before enrolment for non‐recurrrent cohorts), Prior treatment excluded (anti–PD‑1/PD‑L1/CTLA‑4 agents; allogeneic HSCT; prior EZH2 inhibitor except for relapsed cohort). Might simplify: Use statements like "No prior anti‑PD‑1, anti‑PD‑L1, anti‑CTLA‑4 therapy."\n\nGiven complexity, could produce separate spaces for each cancer type plus each disease-status subgroup (three options). That yields many lines. Let\'s enumerate combinations:\n\nCancers:\n1. Atypical teratoid rabhodit tumor – CNS – qualifies under Stratum A.\n   Subspaces: A1 (no recurrence?), actually description: "subjects under consideration for strata A1 or B1...must have evaluable disease". Those seem for pre‑recurrence (?) earlier said "Pre‑recurrent subjects to be enrolled in strata A1, B1, A3, or B3 must be enrolled within 8 weeks of completion of upfront therapy". So A1 = pre‑recurrent with evaluable disease. Similarly A2= relapsed/refractory meas disease. A3=no disease.\n\nHence for ATRT we have three disease status variants: Evaluabl e disease (A1), Measurable disease (A2), No disease (A3). Same pattern for other CNS tumors.\n\nLikewise for extra-CNS tumors (Malignant rhabdoid tumor, Kidney rhabdoid tumor, Epithelioid sarcoma, Chordoma, Others) correspond to Stratum B similarly having B1 eval disease, B2 measurable, B3 no disease.\n\nTherefore total spaces = number_of_cancer_types × 3 disease_statuses.\n\nNumber of cancer types: let\'s list individually:\n\na) Atypical teratoid rhabdoid tumor (CNS)\nb) Other INI1-/SMARCA4-deficient primary CNS malignant tumors (generic CNS)\nc) Malignant rhabdoid tumor (extracranial)\nd) Rhabdoid tumor of the kidney\ne) Epithelial sarcoma (epithelioid sarcoma)\nf) Poorly differentiated or dedifferentiated chordoma\ng) Other INI1-/SMARCA4-deficient malignant tumors (unspecified locations)\n\nThat\'s seven types → 21 spaces.\n\nMay be heavy but doable.\n\nNeed format exactly: numbered list starting 1., 2., ...\n\nEach line: Age range allowed: ..., Sex allowed: ..., Cancer type allowed: ..., Histology allowed: ..., Cancer burden allowed: ..., Prior treatment required: ..., Prior treatment excluded: ..., Biomarkers required: ..., Biomarkers excluded: ....\n\nHistology allowed probably matches cancer type specifics (like "rhabdoid morphology"). May set as same as cancer type name.\n\nLet\'s construct template.\n\nAge range: "≥6\u202fmonths to ≤21\u202fyears"\n\nSex: "Both".\n\nCancer burden depends: "evaluable disease", "measurable disease according to RANO (CNS) or RECIST\xa0v1.1 (extras)", "no evidence of evaluable or measurable disease".\n\nPrior treatment required: For pre‑recurrent/evaluable/no disease cohorts (the ones designated 1 & 3) they must have completed planned upfront therapy and be within 8 weeks of completing upfront therapy. So phrase: "Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy". For measurable disease (relapsed/refractory) there\'s no such requirement—they just need measurable disease; presumably prior therapy already done but not specifically required beyond recovery. To keep simple: "None additional required" i.e., NA.\n\nHowever specification mentions "Subjects must have fully recovered from acute toxic effects of all prior antitumour therapy." That\'s universal but not a strict prerequisite besides health. Maybe omit.\n\nPrior treatment excluded: "Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; prior EZH2 inhibitor therapy (unless enrolling in relapsed/refractory measurable disease cohort [Measurable] )". Because restriction differs: In relapsed/cohort A2/B2, prior EZH2 inhibitor allowed up to 1yr; elsewhere disallowed. Therefore we reflect differently per space.\n\nSimplify: For spaces corresponding to measurable disease (relapsed/refractory) indicate "EZH2 inhibitor therapy allowed up to 1\u202fyear prior". For other spaces say "No prior EZH2 inhibitor therapy".\n\nOk.\n\nBiomarkers required: "Loss of INI1 (by IHC or biallelic SMARCB1 alteration) OR loss of SMARCA4 (by IHC or SMARCA4 alteration)". Indicate assay performed during screening.\n\nBiomarkers excluded: None.\n\nMake sure lists use “and” or “or”. Eg "Loss of INI1 … OR loss of SMARCA4…". Good.\n\nNow build entries enumerating 1..21.\n\nWill be lengthy but fine.\n\nProceed constructing.\n\nNote ensure no commas inside values cause confusion? It\'s ok.\n\nWrite each entry on separate line.\n\nStart numbering sequentially.\n\nI\'ll draft few examples then replicate.\n\nEntry sample:\n\n1. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Atypical teratoid rhabdoid tumor. Histology allowed: Atypical teratoid rhabdoid tumor. Cancer burden allowed: Evaluable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) OR loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessed during screening). Biomarkers excluded: NA.\n\nSecond entry for same cancer type but measurable disease:\n\n2. Age range..., Cancer burden allowed: Measurable disease (per RANO). Prior treatment required: NA. Prior treatment excluded: same list but allow EZH2 inhibitor therapy up to 1\u202fyear prior. So wording: "Any prior anti‑PD‑1…, prior allogeneic HSC transplant; EZH2 inhibitor therapy allowed up to 1\u202fyear prior."\n\nThird entry for no disease:\n\n3. Cancer burden allowed: No evidence of evaluable or measurable disease. Prior treatment required: Completed planned upfront therapy; enrollment within 8\u202fweeks...\n\nContinue for each cancer type.\n\nImportant to adjust evaluation method: For CNS measurable uses RANO; for extracranial uses RECIST v1.1. Mention generically "Measurable disease (according to RANO)" for CNS types, "Measurable disease (according to RECIST v1.1)" for extras.\n\nAlright compile full list.\n\nPotential length ~21 items.\n\nFinally add blank line then Boilerplate exclusions:.\n\nList typical boilerplates derived from exclusion section excluding those captured: Known HIV/hepatitis B/C; uncontrolled intercurrent illness/infection; history of noninfectious pneumonitis needing steroids; active autoimmune disease treated Systemically recent; abnormal CBC suggesting MPN/MDS/ALL; prior myeloid malignancy; prior solid organ transplant; pregnant/breastfeeding; receipt of live/attenuated vaccines within 30 days; allergy to components; inability to comply.\n\nProvide bullet style? Just sentences separated by semicolons? Format unclear—just list each criterion separated by newline maybe. I\'ll follow each item on separate line.\n\nOkay compose answer.assistantfinal1. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Atypical teratoid rhabdoid tumor. Histology allowed: Atypical teratoid rhabdoid tumor. Cancer burden allowed: Evaluable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n2. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Atypical teratoid rhabdoid tumor. Histology allowed: Atypical teratoid rhabdoid tumor. Cancer burden allowed: Measurable disease (defined by RANO). Prior treatment required: NA. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; EZH2 inhibitor therapy allowed up to 1\u202fyear prior. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n3. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Atypical teratoid rhabdoid tumor. Histology allowed: Atypical teratoid rhabdoid tumor. Cancer burden allowed: No evidence of evaluable or measurable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n4. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Other INI1‑deficient or SMARCA4‑deficient primary central nervous system malignant tumor. Histology allowed: Specified primary CNS malignant tumor lacking INI1 or SMARCA4. Cancer burden allowed: Evaluable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n5. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Other INI1‑deficient or SMARCA4‑deficient primary central nervous system malignant tumor. Histology allowed: Specified primary CNS malignant tumor lacking INI1 or SMARCA4. Cancer burden allowed: Measurable disease (defined by RANO). Prior treatment required: NA. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; EZH2 inhibitor therapy allowed up to 1\u202fyear prior. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n6. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Other INI1‑deficient or SMARCA4‑deficient primary central nervous system malignant tumor. Histology allowed: Specified primary CNS malignant tumor lacking INI1 or SMARCA4. Cancer burden allowed: No evidence of evaluable or measurable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n7. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Malignant rhabdoid tumor (extranodal). Histology allowed: Malignant rhabdoid tumor. Cancer burden allowed: Evaluable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n8. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Malignant rhabdoid tumor (extranodal). Histology allowed: Malignant rhabdoid tumor. Cancer burden allowed: Measurable disease (RECIST\u202fv1.1). Prior treatment required: NA. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; EZH2 inhibitor therapy allowed up to 1\u202fyear prior. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n9. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Malignant rhabdoid tumor (extranodal). Histology allowed: Malignant rhabdoid tumor. Cancer burden allowed: No evidence of evaluable or measurable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n10. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Rhabdoid tumor of the kidney. Histology allowed: Rhabdoid tumor of the kidney. Cancer burden allowed: Evaluable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n11. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Rhabdoid tumor of the kidney. Histology allowed: Rhabdoid tumor of the kidney. Cancer burden allowed: Measurable disease (RECIST\u202fv1.1). Prior treatment required: NA. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; EZH2 inhibitor therapy allowed up to 1\u202fyear prior. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n12. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Rhabdoid tumor of the kidney. Histology allowed: Rhabdoid tumor of the kidney. Cancer burden allowed: No evidence of evaluable or measurable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n13. Age range allowed: ≥6\u202fmonths to ≤21\u202fyears. Sex allowed: Both. Cancer type allowed: Epithelioid sarcoma. Histology allowed: Epithelioid sarcoma. Cancer burden allowed: Evaluable disease. Prior treatment required: Completed planned upfront anticancer therapy; enrollment within 8\u202fweeks of completion of upfront therapy. Prior treatment excluded: Any prior anti‑PD‑1, anti‑PD‑L1, anti‑PD‑L2, or anti‑CTLA‑4 therapy; prior allogeneic hematopoietic stem cell transplant; any prior EZH2 inhibitor therapy. Biomarkers required: Loss of INI1 (by IHC or biallelic SMARCB1 alteration) **or** loss of SMARCA4 (by IHC or SMARCA4 alteration) (assessment during screening). Biomarkers excluded: NA.\n\n14. Age range allowed: ≥6\u20