In [2]:
# general imports
import pandas as pd
import os
import json

In [2]:
# Optional environment setup.
# Set these before initializing vLLM, PyTorch, sentence-transformers, or transformers models.

# Restrict this notebook process to specific GPUs.
# Examples: "0" for one GPU, "0,1" for two GPUs.
# os.environ["CUDA_VISIBLE_DEVICES"] = "0"

# Optional: set for higher Hugging Face Hub rate limits and faster first-time downloads.
# os.environ["HF_TOKEN"] = "HF..."

# MMAI Examples

## 1. Trial summarization walkthrough

### Read in data

In [47]:
trials_path = "data/scheduled__2025-09-04T230000+0000.trials_for_summarize.csv"
trials = pd.read_csv(trials_path)
trials = trials.iloc[0:10,]

### Local mode

`summarize_trials(...)` uses the local in-memory vLLM backend by default. Run this cell if you want local mode.

In [4]:
from matchminer_ai.trials import summarize_trials

trial_results, metadata, qc_report = summarize_trials(
    trials, return_metadata=True, return_qc=True
)

# Optional: clear the cached local vLLM engine if GPU memory is tight.
# from matchminer_ai.llm.backends import clear_local_llm_cache
# clear_local_llm_cache()

/home/sabrina/mmai-package/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

INFO 07-06 20:18:57 [utils.py:278] non-default args: {'max_model_len': 30000, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'language_model_only': True, 'model': 'google/gemma-4-31B-it'}
INFO 07-06 20:18:57 [model.py:617] Resolved architecture: Gemma4ForConditionalGeneration
INFO 07-06 20:18:57 [model.py:1752] Using max model len 30000
INFO 07-06 20:19:02 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 07-06 20:19:02 [config.py:100] Gemma4 model has heterogeneous head dimensions (head_dim=256, global_head_dim=512). Forcing TRITON_ATTN backend to prevent mixed-backend numerical divergence.
INFO 07-06 20:19:02 [vllm.py:977] Asynchronous scheduling is enabled.
INFO 07-06 20:19:02 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
WARNING 07-06 20:19:02 [cuda.py:243] Forcing --disable_chunked_mm_input for models with multimodal-bidirectional attention.
INFO 07-06 20:19:02 [registry.py:134] All limits of multimodal modalities supported by the model are set to 0, running in text-only mode.
(EngineCore pid=13378) INFO 07-06 20:19:09 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='google/gemma-4-31B-it', speculative_config=None, tokenizer='google/gemma-4-31B-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=30000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=google/gemma-4-31B-it, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::qwen_gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
(EngineCore pid=13378) INFO 07-06 20:19:09 [parallel_state.py:1422] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.42:58427 backend=nccl
(EngineCore pid=13378) INFO 07-06 20:19:10 [parallel_state.py:1735] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=13378) INFO 07-06 20:19:11 [topk_topp_sampler.py:45] Using FlashInfer for top-p & top-k sampling.
(EngineCore pid=13378) INFO 07-06 20:19:11 [gpu_model_runner.py:5037] Starting to load model google/gemma-4-31B-it...
(EngineCore pid=13378) INFO 07-06 20:19:12 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(EngineCore pid=13378) INFO 07-06 20:19:12 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=13378) INFO 07-06 20:19:12 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=13378) INFO 07-06 20:19:13 [weight_utils.py:922] Filesystem type for checkpoints: EXT4. Checkpoint size: 58.25 GiB. Available RAM: 160.48 GiB.
(EngineCore pid=13378) INFO 07-06 20:19:13 [weight_utils.py:945] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:12<00:12, 12.37s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.20s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.98s/it]
(EngineCore pid=13378)

(EngineCore pid=13378) INFO 07-06 20:19:29 [default_loader.py:397] Loading weights took 16.03 seconds
(EngineCore pid=13378) INFO 07-06 20:19:30 [gpu_model_runner.py:5132] Model loading took 57.91 GiB memory and 17.420215 seconds
(EngineCore pid=13378) INFO 07-06 20:19:38 [backends.py:1089] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/feaa32eb45/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=13378) INFO 07-06 20:19:38 [backends.py:1148] Dynamo bytecode transform time: 7.25 s
(EngineCore pid=13378) INFO 07-06 20:19:42 [backends.py:292] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.255 s
(EngineCore pid=13378) INFO 07-06 20:19:42 [decorators.py:311] Directly load AOT compilation from path /home/sabrina/.cache/vllm/torch_compile_cache/torch_aot_compile/d534beee4da5fd7f6f9f85e08203882408b42b9b2a29243e0663251cb283e805/rank_0_0/model
(EngineCore pid=13378) INFO 07-06 20:19:42 [monitor.py:53] torch.compile took 11.25 s in total
(EngineCore pid=13378) INFO 07-06 20:19:45 [monitor.py:81] Initial profiling/warmup run took 2.45 s
(EngineCore pid=13378) INFO 07-06 20:19:45 [gpu_model_runner.py:6279] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=13378) INFO 07-06 20:19:48 [gpu_model_runner.py:6365] Estimated CUDA graph memory: 0.84 GiB total
(EngineCore pid=13378) INFO 07-06 20:19:49 [gpu_worker.py:466] Available KV cache memory: 11.04 GiB
(EngineCore pid=13378) INFO 07-06 20:19:49 [gpu_worker.py:481] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8895 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9105. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=13378) INFO 07-06 20:19:49 [kv_cache_utils.py:1733] GPU KV cache size: 35,469 tokens
(EngineCore pid=13378) INFO 07-06 20:19:49 [kv_cache_utils.py:1734] Maximum concurrency for 30,000 tokens per request: 1.18x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:07<00:00,  6.92it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:04<00:00,  8.37it/s]

(EngineCore pid=13378) INFO 07-06 20:20:01 [gpu_model_runner.py:6456] Graph capturing finished in 13 secs, took 0.82 GiB
(EngineCore pid=13378) INFO 07-06 20:20:01 [gpu_worker.py:619] CUDA graph pool memory: 0.82 GiB (actual), 0.84 GiB (estimated), difference: 0.02 GiB (2.1%).
(EngineCore pid=13378) INFO 07-06 20:20:02 [jit_monitor.py:54] Kernel JIT monitor activated — Triton JIT compilations during inference will be logged as warnings.
(EngineCore pid=13378) INFO 07-06 20:20:02 [core.py:302] init engine (profile, create kv cache, warmup model) took 31.24 s (compilation: 11.25 s)
(EngineCore pid=13378) INFO 07-06 20:20:02 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

Rendering prompts:   0%|          | 0/10 [00:00<?, ?it/s]

(EngineCore pid=13378) WARNING 07-06 20:20:02 [jit_monitor.py:103] Triton kernel JIT compilation during inference: _compute_slot_mapping_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.
(EngineCore pid=13378) WARNING 07-06 20:20:02 [jit_monitor.py:103] Triton kernel JIT compilation during inference: kernel_unified_attention. This causes a latency spike; consider extending warmup to cover this shape/config.

Rendering prompts: 100%|██████████| 10/10 [00:00<00:00, 93.45it/s]
Processed prompts: 100%|██████████| 10/10 [04:49<00:00, 28.91s/it, est. speed input: 98.08 toks/s, output: 125.52 toks/s]

(EngineCore pid=13378) INFO 07-06 20:25:30 [core.py:1266] Shutdown initiated (timeout=0)
(EngineCore pid=13378) INFO 07-06 20:25:30 [core.py:1289] Shutdown complete

### Remote mode

Run this cell instead of the local-mode cell when you want summarization requests to go to an OpenAI-compatible chat-completions endpoint. The endpoint can be a hosted API, an already-running vLLM server, or a local vLLM server started with the optional helper below.

In [ ]:
from matchminer_ai import load_preset
from matchminer_ai.trials import summarize_trials

config = load_preset("default")
config.remote["enabled"] = True

# Endpoint connection settings. This default points at a local vLLM server.
# For a hosted API, use that provider's base URL and API key instead.
os.environ.setdefault("OPENAI_API_KEY", "not-needed")
config.remote["server_urls"] = ["http://localhost:8000/v1"]

# If the endpoint's request model is not the Hugging Face model ID in
# config.trial["model_name"], set the served API model name here.
# For non-vLLM APIs, leave extra_body empty unless the provider documents it.
# config.trial["remote"].update(
#     {
#         "served_model_name": "your-api-model-name",
#         "max_tokens_param": "max_completion_tokens",
#         "request_params": {"temperature": 0.0},
#         "extra_body": {},
#     }
# )

# Optional: start a local vLLM server for this config if one is not running.
# Leave this commented when using a hosted API or an already-running endpoint.
# from matchminer_ai.llm.vllm_server import start_vllm_server
# os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# process = start_vllm_server(config=config, task="trial")

trial_results, metadata, qc_report = summarize_trials(
    trials, config=config, return_metadata=True, return_qc=True
)

# Optional: stop the local vLLM server if you started it above.
# process.terminate()

### View results

In [5]:
trial_results.head()

,trial_id,clinical_space_number,clinical_space_summary,general_exclusion_criteria,space_trial_id
0,NCT03319901,1,Age range allowed: >= 60 Years. Sex allowed: B...,Poor performance status (eg ECOG > 2)\nHepatic...,NCT03319901-1
1,NCT03319901,2,Age range allowed: >= 60 Years. Sex allowed: B...,Poor performance status (eg ECOG > 2)\nHepatic...,NCT03319901-2
2,NCT03319901,3,Age range allowed: >= 18 Years. Sex allowed: B...,Poor performance status (eg ECOG > 2)\nHepatic...,NCT03319901-3
3,NCT03319901,4,Age range allowed: >= 18 Years. Sex allowed: B...,Poor performance status (eg ECOG > 2)\nHepatic...,NCT03319901-4
4,NCT04792489,1,Age range allowed: 18 years or older. Sex allo...,"Poor performance status (ECOG greater than 1, ...",NCT04792489-1

Metadata contains a snapshot of the config used and metadata on the model used.

In [6]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 30000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 1.0,
     'top_p': 0.95,
     'top_k': 20,
     'min_p': 0.0,
     'presence_penalty': 1.5,
     'max_tokens': 20000,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 1.0,
     'top_p': 0.95,
     'presence_penalty': 1.5},
    'extra_body': {'top_k': 20,
     'min_p': 0.0,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate exclusions'},
  'patient': {'reasoning_parser': 'auto',
   'chunk_size': 50000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 100000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'tokenizer_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate conditions',
   'text_token_threshold': 95000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0526',
   'device': 'cuda',
   'prompt_file': 'embedding.txt',
   'max_seq_length': 2500},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0526',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'max_length': 4096,
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerplateChecker-0526',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt',
   'max_length': 3192},
  'llm_match_quality': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 15000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 15000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_match_quality.user.txt'},
  'llm_exclusion_criteria': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_exclusion_criteria.user.txt'},
  'preset_name': 'default',
  'local': {}},
 'model_metadata': {'trial_summarizer': {'model_name': 'google/gemma-4-31B-it',
   'model_sha': '3548789868c5356dbf307c98e6f609007b82b3eb',
   'created_at': '2026-03-11T18:22:36+00:00',
   'last_modified': '2026-06-03T08:50:40+00:00'}}}

QC report on the trial summarization run

In [7]:
qc_report

,metric,value,denominator,percent,ids
0,trials_missing_in_output,0.0,10.0,0.0,[]
1,trials_truncated_llm_response,0.0,10.0,0.0,[]
2,spaces_exceed_embedding_token_limit,0.0,30.0,0.0,[]
3,spaces_per_trial_min,1.0,NaN,NaN,[]
4,spaces_per_trial_median,2.5,NaN,NaN,[]
5,spaces_per_trial_max,9.0,NaN,NaN,[]
6,trials_with_non_distinct_spaces,0.0,10.0,0.0,[]
7,spaces_dropped_missing_keyword:Age,0.0,30.0,0.0,[]
8,spaces_dropped_missing_keyword:Sex,0.0,30.0,0.0,[]
9,spaces_dropped_missing_keyword:Cancer type,0.0,30.0,0.0,[]
10,spaces_dropped_missing_keyword:Histology,0.0,30.0,0.0,[]
11,spaces_dropped_missing_keyword:Cancer burden,0.0,30.0,0.0,[]
12,spaces_dropped_missing_keyword:Prior treatment...,0.0,30.0,0.0,[]
13,spaces_dropped_missing_keyword:Prior treatment...,0.0,30.0,0.0,[]
14,spaces_dropped_missing_keyword:Biomarkers requ...,0.0,30.0,0.0,[]
15,spaces_dropped_missing_keyword:Biomarkers excl...,0.0,30.0,0.0,[]
16,trials_exclusion_criteria_not_extracted,0.0,10.0,0.0,[]

Save checked-in trial example artifacts

In [8]:
trial_results.to_csv("output/trial_summaries.csv", index=None)
with open("output/trial_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
qc_report.to_csv("output/trial_qc_report.csv", index=None)

## 2. Patient summarization walkthrough

### Read in initial notes

In [3]:
notes_path = "data/note_set_1.csv"
notes = pd.read_csv(notes_path)

### Local mode

`summarize_patients(...)` uses the local in-memory vLLM backend by default. Run this cell if you want local mode.

In [10]:
from matchminer_ai.llm.backends import clear_local_llm_cache
clear_local_llm_cache()

In [18]:
from matchminer_ai.patients import summarize_patients

patient_summaries, metadata, qc_report = summarize_patients(
    notes, return_metadata=True, return_qc=True
)

# Optional: clear the cached local vLLM engine if GPU memory is tight.
# from matchminer_ai.llm.backends import clear_local_llm_cache
# clear_local_llm_cache()

/home/sabrina/mmai-package/src/matchminer_ai/patients/prepare.py:31: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  normalized["note_date"] = pd.to_datetime(normalized["note_date"])
Rendering prompts: 100%|██████████| 12/12 [00:00<00:00, 21.33it/s]
Processed prompts: 100%|██████████| 12/12 [15:28<00:00, 77.35s/it, est. speed input: 220.70 toks/s, output: 35.71 toks/s]

### Remote mode

Run this cell instead of the local-mode cell when you want summarization requests to go to an OpenAI-compatible chat-completions endpoint. The endpoint can be a hosted API, an already-running vLLM server, or a local vLLM server started with the optional helper below.

In [ ]:
from matchminer_ai import load_preset
from matchminer_ai.patients import summarize_patients

config = load_preset("default")
config.remote["enabled"] = True

# Endpoint connection settings. This default points at a local vLLM server.
# For a hosted API, use that provider's base URL and API key instead.
os.environ.setdefault("OPENAI_API_KEY", "not-needed")
config.remote["server_urls"] = ["http://localhost:8000/v1"]

# If the endpoint's request model is not the Hugging Face model ID in
# config.patient["model_name"], set the served API model name here.
# For non-vLLM APIs, leave extra_body empty unless the provider documents it.
# config.patient["remote"].update(
#     {
#         "served_model_name": "your-api-model-name",
#         "max_tokens_param": "max_completion_tokens",
#         "request_params": {"temperature": 0.0},
#         "extra_body": {},
#     }
# )

# Optional: try a quantized Gemma 4 server with speculative decoding for faster
# patient summarization. Use the same config for starting the server and running
# summarization so prompt construction and remote requests stay consistent.
# config.patient["model_name"] = "google/gemma-4-31B-it-qat-w4a16-ct"
# config.patient["reasoning_parser"] = "gemma4"
# config.patient["local"]["engine"]["max_model_len"] = 32768
# config.patient["local"]["engine"]["tensor_parallel_size"] = 2
# config.patient["local"]["engine"]["gpu_memory_utilization"] = 0.40
# qat_extra_args = [
#     "--limit-mm-per-prompt",
#     '{"image": 0, "audio": 0}',
#     "--speculative-config",
#     '{"method": "mtp", "model": "google/gemma-4-31B-it-qat-q4_0-unquantized-assistant", "num_speculative_tokens": 6}',
# ]

# Optional: start a local vLLM server for this config if one is not running.
# Leave this commented when using a hosted API or an already-running endpoint.
# from matchminer_ai.llm.vllm_server import start_vllm_server
# os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
# process = start_vllm_server(
#     config=config,
#     task="patient",
#     extra_args=qat_extra_args,  # omit this argument when using the default model
# )

patient_summaries, metadata, qc_report = summarize_patients(
    notes, config=config, return_metadata=True, return_qc=True
)

# Optional: stop the local vLLM server if you started it above.
# process.terminate()

### Updating existing patient summaries

Run this optional cell after the local- or remote-mode cell above if you want to simulate a longitudinal update. It reads a second set of new notes, uses the existing `patient_summaries` as the starting point, then updates those summaries with the new notes.

In [7]:
from matchminer_ai.patients import summarize_patients

new_notes_path = "data/note_set_2.csv"
new_notes = pd.read_csv(new_notes_path)

existing_summaries = patient_summaries.assign(
    patient_summary=lambda df: (
        df["cancer_history_summary"].fillna("")
        + "\n\nBoilerplate:\n"
        + df["general_exclusion_criteria_evidence"].fillna("")
    )
)[["patient_id", "patient_summary"]]

patient_summaries, metadata, qc_report = summarize_patients(
    new_notes,
    existing_summaries=existing_summaries,
    return_metadata=True,
    return_qc=True,
)

INFO 07-06 22:23:29 [utils.py:278] non-default args: {'max_model_len': 34208, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'language_model_only': True, 'model': 'google/gemma-4-31B-it'}
INFO 07-06 22:23:29 [model.py:617] Resolved architecture: Gemma4ForConditionalGeneration
INFO 07-06 22:23:29 [model.py:1752] Using max model len 34208
INFO 07-06 22:23:34 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 07-06 22:23:34 [config.py:100] Gemma4 model has heterogeneous head dimensions (head_dim=256, global_head_dim=512). Forcing TRITON_ATTN backend to prevent mixed-backend numerical divergence.
INFO 07-06 22:23:34 [vllm.py:977] Asynchronous scheduling is enabled.
INFO 07-06 22:23:34 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
WARNING 07-06 22:23:34 [cuda.py:243] Forcing --disable_chunked_mm_input for models with multimodal-bidirectional attention.
INFO 07-06 22:23:35 [registry.py:134] All limits of multimodal modalities supported by the model are set to 0, running in text-only mode.
(EngineCore pid=45162) INFO 07-06 22:23:41 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='google/gemma-4-31B-it', speculative_config=None, tokenizer='google/gemma-4-31B-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=34208, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=google/gemma-4-31B-it, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::qwen_gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')
(EngineCore pid=45162) INFO 07-06 22:23:42 [parallel_state.py:1422] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.42:49005 backend=nccl
(EngineCore pid=45162) INFO 07-06 22:23:42 [parallel_state.py:1735] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=45162) INFO 07-06 22:23:43 [topk_topp_sampler.py:45] Using FlashInfer for top-p & top-k sampling.
(EngineCore pid=45162) INFO 07-06 22:23:43 [gpu_model_runner.py:5037] Starting to load model google/gemma-4-31B-it...
(EngineCore pid=45162) INFO 07-06 22:23:44 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(EngineCore pid=45162) INFO 07-06 22:23:44 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=45162) INFO 07-06 22:23:44 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=45162) INFO 07-06 22:23:45 [weight_utils.py:922] Filesystem type for checkpoints: EXT4. Checkpoint size: 58.25 GiB. Available RAM: 150.28 GiB.
(EngineCore pid=45162) INFO 07-06 22:23:45 [weight_utils.py:945] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:12<00:12, 12.27s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.15s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.92s/it]
(EngineCore pid=45162)

(EngineCore pid=45162) INFO 07-06 22:24:01 [default_loader.py:397] Loading weights took 15.92 seconds
(EngineCore pid=45162) INFO 07-06 22:24:02 [gpu_model_runner.py:5132] Model loading took 57.91 GiB memory and 17.264348 seconds
(EngineCore pid=45162) INFO 07-06 22:24:10 [backends.py:1089] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/76884c0395/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=45162) INFO 07-06 22:24:10 [backends.py:1148] Dynamo bytecode transform time: 7.11 s
(EngineCore pid=45162) INFO 07-06 22:24:14 [backends.py:292] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.211 s
(EngineCore pid=45162) INFO 07-06 22:24:14 [decorators.py:311] Directly load AOT compilation from path /home/sabrina/.cache/vllm/torch_compile_cache/torch_aot_compile/f70134b0046169638aed928c4357c3f46ef02ab7c2e1ee3e804b854ad439a1ef/rank_0_0/model
(EngineCore pid=45162) INFO 07-06 22:24:14 [monitor.py:53] torch.compile took 11.07 s in total
(EngineCore pid=45162) INFO 07-06 22:24:16 [monitor.py:81] Initial profiling/warmup run took 2.46 s
(EngineCore pid=45162) INFO 07-06 22:24:17 [gpu_model_runner.py:6279] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=45162) INFO 07-06 22:24:20 [gpu_model_runner.py:6365] Estimated CUDA graph memory: 0.84 GiB total
(EngineCore pid=45162) INFO 07-06 22:24:21 [gpu_worker.py:466] Available KV cache memory: 11.04 GiB
(EngineCore pid=45162) INFO 07-06 22:24:21 [gpu_worker.py:481] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8895 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9105. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=45162) INFO 07-06 22:24:21 [kv_cache_utils.py:1733] GPU KV cache size: 39,104 tokens
(EngineCore pid=45162) INFO 07-06 22:24:21 [kv_cache_utils.py:1734] Maximum concurrency for 34,208 tokens per request: 1.14x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:07<00:00,  6.94it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:04<00:00,  8.30it/s]

(EngineCore pid=45162) INFO 07-06 22:24:33 [gpu_model_runner.py:6456] Graph capturing finished in 13 secs, took 0.82 GiB
(EngineCore pid=45162) INFO 07-06 22:24:33 [gpu_worker.py:619] CUDA graph pool memory: 0.82 GiB (actual), 0.84 GiB (estimated), difference: 0.02 GiB (2.1%).
(EngineCore pid=45162) INFO 07-06 22:24:34 [jit_monitor.py:54] Kernel JIT monitor activated — Triton JIT compilations during inference will be logged as warnings.
(EngineCore pid=45162) INFO 07-06 22:24:34 [core.py:302] init engine (profile, create kv cache, warmup model) took 31.25 s (compilation: 11.07 s)
(EngineCore pid=45162) INFO 07-06 22:24:34 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

Rendering prompts:   0%|          | 0/12 [00:00<?, ?it/s]

(EngineCore pid=45162) WARNING 07-06 22:24:34 [jit_monitor.py:103] Triton kernel JIT compilation during inference: _compute_slot_mapping_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.
(EngineCore pid=45162) WARNING 07-06 22:24:34 [jit_monitor.py:103] Triton kernel JIT compilation during inference: kernel_unified_attention. This causes a latency spike; consider extending warmup to cover this shape/config.

Rendering prompts: 100%|██████████| 12/12 [00:00<00:00, 30.98it/s]
Processed prompts: 100%|██████████| 12/12 [11:44<00:00, 58.74s/it, est. speed input: 201.08 toks/s, output: 49.50 toks/s]

### View results

In [8]:
patient_summaries.head()

,patient_id,last_note_date,cancer_history_summary,general_exclusion_criteria_evidence
0,11609,2026-05-03,Age: 71\nSex: Female\nCancer type: Glioblastom...,ECOG 4. Essential hypertension. Hyperlipidemia...
1,12019,2026-05-14,Age: 52\nSex: Female\nCancer type: Breast canc...,"Hypertension, hyperlipidemia, Grade 2 ribocicl..."
2,15687,2025-10-07,Age: 68\nSex: Male\nCancer type: Lung cancer\n...,ECOG 1-2. Hypertension. Hyperlipidemia. Osteop...
3,16916000000,2024-11-14,Age: 21\nSex: Male\nCancer type: Osteosarcoma\...,ECOG 0. History of grade 2 immune-mediated col...
4,1722,2025-02-10,Age: 64\nSex: Male\nCancer type: Gastro-esopha...,ECOG 1. Hypertension. Hyperlipidemia. Immune-r...

Metadata contains a snapshot of the config used and metadata on the models used.

In [9]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 30000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 1.0,
     'top_p': 0.95,
     'top_k': 20,
     'min_p': 0.0,
     'presence_penalty': 1.5,
     'max_tokens': 20000,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 1.0,
     'top_p': 0.95,
     'presence_penalty': 1.5},
    'extra_body': {'top_k': 20,
     'min_p': 0.0,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate exclusions'},
  'patient': {'reasoning_parser': 'auto',
   'chunk_size': 50000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 34208,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'tokenizer_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate conditions',
   'text_token_threshold': 95000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0526',
   'device': 'cuda',
   'prompt_file': 'embedding.txt',
   'max_seq_length': 2500},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0526',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'max_length': 4096,
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerplateChecker-0526',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt',
   'max_length': 3192},
  'llm_match_quality': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 15000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 15000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_match_quality.user.txt'},
  'llm_exclusion_criteria': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_exclusion_criteria.user.txt'},
  'preset_name': 'default',
  'local': {}},
 'model_metadata': {'patient_summarizer': {'model_name': 'google/gemma-4-31B-it',
   'model_sha': '3548789868c5356dbf307c98e6f609007b82b3eb',
   'created_at': '2026-03-11T18:22:36+00:00',
   'last_modified': '2026-06-03T08:50:40+00:00'}}}

QC report on patient summarization

In [10]:
qc_report

                                       metric  value  denominator  percent ids
0       patients_exceed_embedding_token_limit      0           12      0.0  []
1   patients_exclusion_criteria_not_extracted      0           12      0.0  []
2                patients_missing_keyword:Age      0           12      0.0  []
3                patients_missing_keyword:Sex      0           12      0.0  []
4        patients_missing_keyword:Cancer type      0           12      0.0  []
5          patients_missing_keyword:Histology      0           12      0.0  []
6     patients_missing_keyword:Current extent      0           12      0.0  []
7         patients_missing_keyword:Biomarkers      0           12      0.0  []
8  patients_missing_keyword:Treatment history      0           12      0.0  []

Save checked-in patient example artifacts

In [11]:
patient_summaries.to_csv("output/patient_summaries.csv", index=None)
with open("output/patient_summarization_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
qc_report.to_csv("output/patient_qc_report.csv", index=None)

## 3. Embed summarized entities for matching

In [13]:
from matchminer_ai.embedding import embed_for_matching

In [ ]:
# Uncomment if you want to start from previously generated summaries
# trial_results = pd.read_csv("output/trial_summaries.csv")
# patient_summaries = pd.read_csv("output/patient_summaries.csv", dtype="str")

### Trials

In [16]:
embedded_trials, metadata = embed_for_matching(
    trial_results, entity_type="trial", return_metadata=True
)

Loading weights: 100%|██████████| 310/310 [00:00<00:00, 881.08it/s]

In [17]:
embedded_trials.head()

  space_trial_id                                          embedding
0  NCT03319901-1  [-0.024169921875, -0.041748046875, 0.004364013...
1  NCT03319901-2  [0.0106201171875, 0.008056640625, 0.0078125, 0...
2  NCT03319901-3  [-0.003021240234375, -0.0142822265625, 0.00805...
3  NCT03319901-4  [0.03857421875, 0.04443359375, 0.011962890625,...
4  NCT04792489-1  [-0.025390625, -0.03466796875, 0.0046691894531...

Metadata contains a snapshot of the config used and metadata on the models used.

In [18]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 30000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 1.0,
     'top_p': 0.95,
     'top_k': 20,
     'min_p': 0.0,
     'presence_penalty': 1.5,
     'max_tokens': 20000,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 1.0,
     'top_p': 0.95,
     'presence_penalty': 1.5},
    'extra_body': {'top_k': 20,
     'min_p': 0.0,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate exclusions'},
  'patient': {'reasoning_parser': 'auto',
   'chunk_size': 50000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 34208,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'tokenizer_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate conditions',
   'text_token_threshold': 95000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0526',
   'device': 'cuda',
   'prompt_file': 'embedding.txt',
   'max_seq_length': 2500},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0526',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'max_length': 4096,
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerplateChecker-0526',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt',
   'max_length': 3192},
  'llm_match_quality': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 15000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 15000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_match_quality.user.txt'},
  'llm_exclusion_criteria': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_exclusion_criteria.user.txt'},
  'preset_name': 'default',
  'local': {}},
 'model_metadata': {'embedding_model': {'model_name': 'ksg-dfci/TrialSpace-0526',
   'model_sha': 'cf4c59145eeece9983e33816a9f813110b89a68a',
   'created_at': '2026-05-29T16:51:45+00:00',
   'last_modified': '2026-05-29T16:56:24+00:00'}}}

### Patients

In [19]:
embedded_patients, metadata = embed_for_matching(
    patient_summaries, entity_type="patient", return_metadata=True
)

In [20]:
embedded_patients.head()

    patient_id                                          embedding
0        11609  [-0.01123046875, 0.00958251953125, -0.00549316...
1        12019  [-0.056396484375, 0.0458984375, -0.00811767578...
2        15687  [0.0145263671875, -0.01171875, -0.004821777343...
3  16916000000  [0.061279296875, -0.00078582763671875, -0.0046...
4         1722  [0.0147705078125, 0.048095703125, -0.003433227...

Metadata contains a snapshot of the config used and metadata on the models used.

In [21]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 30000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 1.0,
     'top_p': 0.95,
     'top_k': 20,
     'min_p': 0.0,
     'presence_penalty': 1.5,
     'max_tokens': 20000,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 1.0,
     'top_p': 0.95,
     'presence_penalty': 1.5},
    'extra_body': {'top_k': 20,
     'min_p': 0.0,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate exclusions'},
  'patient': {'reasoning_parser': 'auto',
   'chunk_size': 50000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 34208,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'tokenizer_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate conditions',
   'text_token_threshold': 95000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0526',
   'device': 'cuda',
   'prompt_file': 'embedding.txt',
   'max_seq_length': 2500},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0526',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'max_length': 4096,
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerplateChecker-0526',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt',
   'max_length': 3192},
  'llm_match_quality': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 15000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 15000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_match_quality.user.txt'},
  'llm_exclusion_criteria': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_exclusion_criteria.user.txt'},
  'preset_name': 'default',
  'local': {}},
 'model_metadata': {'embedding_model': {'model_name': 'ksg-dfci/TrialSpace-0526',
   'model_sha': 'cf4c59145eeece9983e33816a9f813110b89a68a',
   'created_at': '2026-05-29T16:51:45+00:00',
   'last_modified': '2026-05-29T16:56:24+00:00'}}}

In [22]:
# Optional local export if you want to reuse embeddings without rerunning this step.
embedded_patients.to_parquet("output/embedded_patients.parquet")
embedded_trials.to_parquet("output/embedded_trials.parquet")

## 4. Generate candidate matches

Generate ranked trial-space candidates for each patient.

In [23]:
from matchminer_ai.matching import generate_candidate_matches

In [24]:
# Uncomment if you saved embeddings locally and want to start from them
# embedded_patients = pd.read_parquet('output/embedded_patients.parquet')
# embedded_trials = pd.read_parquet('output/embedded_trials.parquet')

### Candidate matches

In [25]:
candidate_matches = generate_candidate_matches(
    query_df=embedded_patients, corpus_df=embedded_trials
)

In [26]:
candidate_matches.head()

  patient_id space_trial_id  similarity_score  rank
0      11609  NCT05785741-1          0.392849     1
1      11609  NCT05538130-1          0.358549     2
2      11609  NCT06234423-2          0.338900     3
3      11609  NCT05538130-3          0.310116     4
4      11609  NCT04792489-6          0.213226     5

## 5. Match quality check

### Classifier-based match-quality check

Run the trained classifier checker after adding patient and trial summary context.

In [27]:
from matchminer_ai.matching import score_match_quality

Add back the patient and trial summary context required by the match-quality checker.

In [28]:
candidate_matches_with_context = (
    candidate_matches.merge(
        patient_summaries[["patient_id", "cancer_history_summary"]],
        on="patient_id",
        how="left",
    ).merge(
        trial_results[["space_trial_id", "clinical_space_summary"]],
        on="space_trial_id",
        how="left",
    )
)
candidate_matches_with_context.head()

,patient_id,space_trial_id,similarity_score,rank,cancer_history_summary,clinical_space_summary
0,11609,NCT05785741-1,0.392849,1,Age: 71\nSex: Female\nCancer type: Glioblastom...,Age range allowed: 18 years or older. Sex allo...
1,11609,NCT05538130-1,0.358549,2,Age: 71\nSex: Female\nCancer type: Glioblastom...,Age range allowed: NA. Sex allowed: Both. Canc...
2,11609,NCT06234423-2,0.338900,3,Age: 71\nSex: Female\nCancer type: Glioblastom...,Age range allowed: >=18 years. Sex allowed: Ma...
3,11609,NCT05538130-3,0.310116,4,Age: 71\nSex: Female\nCancer type: Glioblastom...,Age range allowed: NA. Sex allowed: Both. Canc...
4,11609,NCT04792489-6,0.213226,5,Age: 71\nSex: Female\nCancer type: Glioblastom...,Age range allowed: 18 years or older. Sex allo...

Run the match-quality checker.

In [29]:
match_quality_matches, metadata = score_match_quality(
    candidate_matches_with_context, return_metadata=True
)

Loading weights: 100%|██████████| 174/174 [00:00<00:00, 900.51it/s]

In [30]:
match_quality_matches.head()

  patient_id space_trial_id  match_quality_score  match_quality_pass
0      11609  NCT05785741-1             0.544794                True
1      11609  NCT05538130-1             0.449333                True
2      11609  NCT06234423-2             0.439996                True
3      12019  NCT05608252-1             0.998750                True
4      12019  NCT05538130-1             0.399403                True

In [31]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 30000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 1.0,
     'top_p': 0.95,
     'top_k': 20,
     'min_p': 0.0,
     'presence_penalty': 1.5,
     'max_tokens': 20000,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 1.0,
     'top_p': 0.95,
     'presence_penalty': 1.5},
    'extra_body': {'top_k': 20,
     'min_p': 0.0,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate exclusions'},
  'patient': {'reasoning_parser': 'auto',
   'chunk_size': 50000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 34208,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'tokenizer_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate conditions',
   'text_token_threshold': 95000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0526',
   'device': 'cuda',
   'prompt_file': 'embedding.txt',
   'max_seq_length': 2500},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0526',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'max_length': 4096,
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerplateChecker-0526',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt',
   'max_length': 3192},
  'llm_match_quality': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 15000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 15000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_match_quality.user.txt'},
  'llm_exclusion_criteria': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.95,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_exclusion_criteria.user.txt'},
  'preset_name': 'default',
  'local': {}},
 'model_metadata': {'match_quality_checker': {'model_name': 'ksg-dfci/TrialChecker-0526',
   'model_sha': 'a87933dc3cd1bc0eabd05f30794b514180d14598',
   'created_at': '2026-05-29T16:53:30+00:00',
   'last_modified': '2026-05-29T16:58:21+00:00'}}}

### LLM-based match-quality check

This optional checker uses the configured LLM backend instead of the classifier checker. Debug mode includes raw response columns for reviewing parsed scores; separate reasoning columns are populated only when the backend returns reasoning content.

In [34]:
from matchminer_ai.matching import score_match_quality_with_llm

llm_match_quality_matches, llm_match_quality_metadata = score_match_quality_with_llm(
    candidate_matches_with_context,
    return_metadata=True,
)

INFO 07-06 23:24:24 [utils.py:278] non-default args: {'max_model_len': 50000, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'language_model_only': True, 'model': 'google/gemma-4-31B-it'}

INFO 07-06 23:24:25 [model.py:617] Resolved architecture: Gemma4ForConditionalGeneration
INFO 07-06 23:24:25 [model.py:1752] Using max model len 50000
INFO 07-06 23:24:25 [config.py:100] Gemma4 model has heterogeneous head dimensions (head_dim=256, global_head_dim=512). Forcing TRITON_ATTN backend to prevent mixed-backend numerical divergence.
INFO 07-06 23:24:25 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
WARNING 07-06 23:24:25 [cuda.py:243] Forcing --disable_chunked_mm_input for models with multimodal-bidirectional attention.
(EngineCore pid=58964) INFO 07-06 23:24:39 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='google/gemma-4-31B-it', speculative_config=None, tokenizer='google/gemma-4-31B-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=50000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=google/gemma-4-31B-it, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::qwen_gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')

(EngineCore pid=58964) Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

(EngineCore pid=58964) INFO 07-06 23:24:45 [registry.py:134] All limits of multimodal modalities supported by the model are set to 0, running in text-only mode.
(EngineCore pid=58964) INFO 07-06 23:24:45 [parallel_state.py:1422] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.42:42377 backend=nccl
(EngineCore pid=58964) INFO 07-06 23:24:45 [parallel_state.py:1735] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=58964) INFO 07-06 23:24:46 [topk_topp_sampler.py:45] Using FlashInfer for top-p & top-k sampling.
(EngineCore pid=58964) INFO 07-06 23:24:46 [gpu_model_runner.py:5037] Starting to load model google/gemma-4-31B-it...
(EngineCore pid=58964) INFO 07-06 23:24:47 [vllm.py:977] Asynchronous scheduling is enabled.
(EngineCore pid=58964) INFO 07-06 23:24:47 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(EngineCore pid=58964) INFO 07-06 23:24:47 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=58964) INFO 07-06 23:24:47 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=58964) INFO 07-06 23:24:48 [weight_utils.py:922] Filesystem type for checkpoints: EXT4. Checkpoint size: 58.25 GiB. Available RAM: 155.77 GiB.
(EngineCore pid=58964) INFO 07-06 23:24:48 [weight_utils.py:945] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:12<00:12, 12.29s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.16s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.93s/it]
(EngineCore pid=58964)

(EngineCore pid=58964) INFO 07-06 23:25:04 [default_loader.py:397] Loading weights took 15.94 seconds
(EngineCore pid=58964) INFO 07-06 23:25:05 [gpu_model_runner.py:5132] Model loading took 57.91 GiB memory and 17.065205 seconds
(EngineCore pid=58964) INFO 07-06 23:25:12 [backends.py:1089] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/43d3a514d4/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=58964) INFO 07-06 23:25:12 [backends.py:1148] Dynamo bytecode transform time: 6.95 s
(EngineCore pid=58964) INFO 07-06 23:25:16 [backends.py:292] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 2.813 s
(EngineCore pid=58964) INFO 07-06 23:25:16 [decorators.py:311] Directly load AOT compilation from path /home/sabrina/.cache/vllm/torch_compile_cache/torch_aot_compile/78cdf589f6d2d203da5a188bd914d969bba62f70816af1655edf763f177c4a3d/rank_0_0/model
(EngineCore pid=58964) INFO 07-06 23:25:16 [monitor.py:53] torch.compile took 10.50 s in total
(EngineCore pid=58964) INFO 07-06 23:25:18 [monitor.py:81] Initial profiling/warmup run took 2.25 s
(EngineCore pid=58964) INFO 07-06 23:25:19 [gpu_model_runner.py:6279] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=58964) INFO 07-06 23:25:21 [gpu_model_runner.py:6365] Estimated CUDA graph memory: 0.84 GiB total
(EngineCore pid=58964) INFO 07-06 23:25:21 [gpu_worker.py:466] Available KV cache memory: 11.04 GiB
(EngineCore pid=58964) INFO 07-06 23:25:21 [gpu_worker.py:481] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8895 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9105. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=58964) INFO 07-06 23:25:21 [kv_cache_utils.py:1733] GPU KV cache size: 50,809 tokens
(EngineCore pid=58964) INFO 07-06 23:25:21 [kv_cache_utils.py:1734] Maximum concurrency for 50,000 tokens per request: 1.02x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:07<00:00,  6.98it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:04<00:00,  8.48it/s]

(EngineCore pid=58964) INFO 07-06 23:25:34 [gpu_model_runner.py:6456] Graph capturing finished in 13 secs, took 0.82 GiB
(EngineCore pid=58964) INFO 07-06 23:25:34 [gpu_worker.py:619] CUDA graph pool memory: 0.82 GiB (actual), 0.84 GiB (estimated), difference: 0.02 GiB (2.1%).
(EngineCore pid=58964) INFO 07-06 23:25:34 [jit_monitor.py:54] Kernel JIT monitor activated — Triton JIT compilations during inference will be logged as warnings.
(EngineCore pid=58964) INFO 07-06 23:25:34 [core.py:302] init engine (profile, create kv cache, warmup model) took 29.40 s (compilation: 10.50 s)
(EngineCore pid=58964) INFO 07-06 23:25:35 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

Rendering prompts:  12%|█▏        | 28/240 [00:00<00:00, 272.55it/s]

(EngineCore pid=58964) WARNING 07-06 23:25:35 [jit_monitor.py:103] Triton kernel JIT compilation during inference: _compute_slot_mapping_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.
(EngineCore pid=58964) WARNING 07-06 23:25:35 [jit_monitor.py:103] Triton kernel JIT compilation during inference: kernel_unified_attention. This causes a latency spike; consider extending warmup to cover this shape/config.

Rendering prompts: 100%|██████████| 240/240 [00:00<00:00, 286.61it/s]
Processed prompts: 100%|██████████| 240/240 [15:36<00:00,  3.90s/it, est. speed input: 358.61 toks/s, output: 191.64 toks/s]

In [35]:
llm_match_quality_matches.head()

  patient_id space_trial_id  llm_match_quality_score
0      11609  NCT05785741-1                        2
1      11609  NCT05538130-1                        2
2      11609  NCT06234423-2                        2
3      11609  NCT05538130-3                        0
4      11609  NCT04792489-6                        0

## 6. Exclusion criteria check

### Classifier-based exclusion criteria check

Run the trained classifier checker after adding patient and trial exclusion-criteria context.

In [36]:
# limit to unique patient-trial ID pairs
match_quality_matches["trial_id"] = (
    match_quality_matches["space_trial_id"].str.split("-").str[0]
)
unique_patient_trial_pairs = match_quality_matches[
    ["patient_id", "trial_id"]
].drop_duplicates()

# add in exclusion criteria for patients and trials
patient_trial_pairs_with_exclusion_context = unique_patient_trial_pairs.merge(
    patient_summaries[["patient_id", "general_exclusion_criteria_evidence"]],
    on="patient_id",
    how="left",
).merge(
    trial_results[["trial_id", "general_exclusion_criteria"]].drop_duplicates(),
    on="trial_id",
    how="left",
)
patient_trial_pairs_with_exclusion_context.head()

,patient_id,trial_id,general_exclusion_criteria_evidence,general_exclusion_criteria
0,11609,NCT05785741,ECOG 4. Essential hypertension. Hyperlipidemia...,Poor performance status (eg ECOG >1).\nLeft ve...
1,11609,NCT05538130,ECOG 4. Essential hypertension. Hyperlipidemia...,Brain metastasis larger than 4 cm\nHistory or ...
2,11609,NCT06234423,ECOG 4. Essential hypertension. Hyperlipidemia...,Poor performance status (ECOG > 1).\nActive or...
3,12019,NCT05608252,"Hypertension, hyperlipidemia, Grade 2 ribocicl...",Poor performance status (ECOG >= 2).\nActive b...
4,12019,NCT05538130,"Hypertension, hyperlipidemia, Grade 2 ribocicl...",Brain metastasis larger than 4 cm\nHistory or ...

In [37]:
from matchminer_ai.matching import exclusion_criteria_check

# run exclusion criteria check
exclusion_results, metadata = exclusion_criteria_check(
    patient_trial_pairs_with_exclusion_context, return_metadata=True
)
exclusion_results.head()

Loading weights: 100%|██████████| 174/174 [00:00<00:00, 847.31it/s]

  patient_id     trial_id  exclusion_score  exclusion_criteria_pass
0      11609  NCT05785741         0.999998                    False
1      11609  NCT05538130         0.999984                     True
2      11609  NCT06234423         0.999999                    False
3      12019  NCT05608252         0.999361                     True
4      12019  NCT05538130         0.999989                     True

In [38]:
exclusion_results["exclusion_criteria_pass"].value_counts()

exclusion_criteria_pass
True     29
False     6
Name: count, dtype: int64

In [39]:
metadata

{'config_snapshot': {'version': 0,
  'debug_mode': False,
  'model_metadata_cache_dir': '.mmai_cache/model_metadata',
  'remote': {'enabled': False,
   'server_urls': ['http://localhost:8000/v1'],
   'max_concurrent_requests': 16,
   'request_timeout': 600,
   'max_retries': 6,
   'batch_size': 1000,
   'retry_backoff_base': 1.0},
  'trial': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 30000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 1.0,
     'top_p': 0.95,
     'top_k': 20,
     'min_p': 0.0,
     'presence_penalty': 1.5,
     'max_tokens': 20000,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 1.0,
     'top_p': 0.95,
     'presence_penalty': 1.5},
    'extra_body': {'top_k': 20,
     'min_p': 0.0,
     'repetition_penalty': 1.0,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'trial.user.primer.txt',
    'question': 'trial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate exclusions'},
  'patient': {'reasoning_parser': 'auto',
   'chunk_size': 50000,
   'chunk_overlap': 500,
   'prompt_margin_tokens': 5000,
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 34208,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'tokenizer_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_files': {'primer': 'patient.serial.user.primer.txt',
    'question': 'patient.serial.user.question.txt'},
   'boilerplate_marker': 'Boilerplate conditions',
   'text_token_threshold': 95000},
  'embedding': {'model_path': 'ksg-dfci/TrialSpace-0526',
   'device': 'cuda',
   'prompt_file': 'embedding.txt',
   'max_seq_length': 2500},
  'match_quality': {'model_name': 'ksg-dfci/TrialChecker-0526',
   'device': 'cuda',
   'prompt_file': 'match_quality_checker_template.txt',
   'max_length': 4096,
   'score_cutoff': 0.2},
  'exclusion_criteria': {'model_name': 'ksg-dfci/BoilerplateChecker-0526',
   'device': 'cuda',
   'prompt_file': 'exclusion_criteria_checker_template.txt',
   'max_length': 3192},
  'llm_match_quality': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 15000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 15000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_match_quality.user.txt'},
  'llm_exclusion_criteria': {'reasoning_parser': 'auto',
   'local': {'model_name': 'google/gemma-4-31B-it',
    'engine': {'max_model_len': 50000,
     'tensor_parallel_size': 1,
     'gpu_memory_utilization': 0.9,
     'language_model_only': True},
    'chat_template_kwargs': {'enable_thinking': True},
    'generation': {'temperature': 0.0,
     'top_k': 1,
     'top_p': 1.0,
     'presence_penalty': 0.0,
     'min_p': 0.0,
     'max_tokens': 20000,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False}},
   'remote': {'model_name': 'google/gemma-4-31B-it',
    'request_params': {'max_tokens': 20000,
     'temperature': 0.0,
     'top_p': 1.0,
     'presence_penalty': 0.0},
    'extra_body': {'top_k': 1,
     'min_p': 0.0,
     'repetition_penalty': 1.1,
     'skip_special_tokens': False,
     'chat_template_kwargs': {'enable_thinking': True}}},
   'prompt_file': 'llm_exclusion_criteria.user.txt'},
  'preset_name': 'default',
  'local': {}},
 'model_metadata': {'exclusion_criteria_checker': {'model_name': 'ksg-dfci/BoilerplateChecker-0526',
   'model_sha': 'cf6cdd74058f1b3a135702debc0817e289f0ee09',
   'created_at': '2026-05-29T16:54:16+00:00',
   'last_modified': '2026-05-29T16:59:13+00:00'}}}

### LLM-based exclusion criteria check

This optional checker uses the configured LLM backend instead of the classifier checker and returns whether each patient-trial pair passes exclusion criteria.

In [44]:
from matchminer_ai.matching import exclusion_criteria_check_with_llm

llm_exclusion_results, llm_exclusion_metadata = exclusion_criteria_check_with_llm(
    patient_trial_pairs_with_exclusion_context,
    return_metadata=True,
)

INFO 07-07 01:59:24 [utils.py:278] non-default args: {'max_model_len': 50000, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'language_model_only': True, 'model': 'google/gemma-4-31B-it'}

INFO 07-07 01:59:25 [model.py:617] Resolved architecture: Gemma4ForConditionalGeneration
INFO 07-07 01:59:25 [model.py:1752] Using max model len 50000
INFO 07-07 01:59:25 [config.py:100] Gemma4 model has heterogeneous head dimensions (head_dim=256, global_head_dim=512). Forcing TRITON_ATTN backend to prevent mixed-backend numerical divergence.
INFO 07-07 01:59:25 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
WARNING 07-07 01:59:25 [cuda.py:243] Forcing --disable_chunked_mm_input for models with multimodal-bidirectional attention.
(EngineCore pid=86957) INFO 07-07 01:59:40 [core.py:112] Initializing a V1 LLM engine (v0.22.0) with config: model='google/gemma-4-31B-it', speculative_config=None, tokenizer='google/gemma-4-31B-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=50000, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=google/gemma-4-31B-it, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::qwen_gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto', linear_backend='auto')

(EngineCore pid=86957) Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

(EngineCore pid=86957) INFO 07-07 01:59:46 [registry.py:134] All limits of multimodal modalities supported by the model are set to 0, running in text-only mode.
(EngineCore pid=86957) INFO 07-07 01:59:46 [parallel_state.py:1422] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.0.42:32791 backend=nccl
(EngineCore pid=86957) INFO 07-07 01:59:46 [parallel_state.py:1735] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=86957) INFO 07-07 01:59:47 [topk_topp_sampler.py:45] Using FlashInfer for top-p & top-k sampling.
(EngineCore pid=86957) INFO 07-07 01:59:47 [gpu_model_runner.py:5037] Starting to load model google/gemma-4-31B-it...
(EngineCore pid=86957) INFO 07-07 01:59:48 [vllm.py:977] Asynchronous scheduling is enabled.
(EngineCore pid=86957) INFO 07-07 01:59:48 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(EngineCore pid=86957) INFO 07-07 01:59:48 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=86957) INFO 07-07 01:59:48 [cuda.py:318] Using AttentionBackendEnum.TRITON_ATTN backend.
(EngineCore pid=86957) INFO 07-07 01:59:49 [weight_utils.py:922] Filesystem type for checkpoints: EXT4. Checkpoint size: 58.25 GiB. Available RAM: 158.18 GiB.
(EngineCore pid=86957) INFO 07-07 01:59:49 [weight_utils.py:945] Auto-prefetch is disabled because the filesystem (EXT4) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:12<00:12, 12.37s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.20s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:15<00:00,  7.98s/it]
(EngineCore pid=86957)

(EngineCore pid=86957) INFO 07-07 02:00:05 [default_loader.py:397] Loading weights took 16.02 seconds
(EngineCore pid=86957) INFO 07-07 02:00:05 [gpu_model_runner.py:5132] Model loading took 57.91 GiB memory and 17.164154 seconds
(EngineCore pid=86957) INFO 07-07 02:00:13 [backends.py:1089] Using cache directory: /home/sabrina/.cache/vllm/torch_compile_cache/43d3a514d4/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=86957) INFO 07-07 02:00:13 [backends.py:1148] Dynamo bytecode transform time: 6.96 s
(EngineCore pid=86957) INFO 07-07 02:00:16 [backends.py:292] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 2.708 s
(EngineCore pid=86957) INFO 07-07 02:00:16 [decorators.py:311] Directly load AOT compilation from path /home/sabrina/.cache/vllm/torch_compile_cache/torch_aot_compile/78cdf589f6d2d203da5a188bd914d969bba62f70816af1655edf763f177c4a3d/rank_0_0/model
(EngineCore pid=86957) INFO 07-07 02:00:16 [monitor.py:53] torch.compile took 10.41 s in total
(EngineCore pid=86957) INFO 07-07 02:00:19 [monitor.py:81] Initial profiling/warmup run took 2.27 s
(EngineCore pid=86957) INFO 07-07 02:00:19 [gpu_model_runner.py:6279] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=86957) INFO 07-07 02:00:22 [gpu_model_runner.py:6365] Estimated CUDA graph memory: 0.84 GiB total
(EngineCore pid=86957) INFO 07-07 02:00:22 [gpu_worker.py:466] Available KV cache memory: 11.04 GiB
(EngineCore pid=86957) INFO 07-07 02:00:22 [gpu_worker.py:481] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8895 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9105. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
(EngineCore pid=86957) INFO 07-07 02:00:22 [kv_cache_utils.py:1733] GPU KV cache size: 50,809 tokens
(EngineCore pid=86957) INFO 07-07 02:00:22 [kv_cache_utils.py:1734] Maximum concurrency for 50,000 tokens per request: 1.02x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 51/51 [00:07<00:00,  6.91it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 35/35 [00:04<00:00,  8.44it/s]

(EngineCore pid=86957) INFO 07-07 02:00:35 [gpu_model_runner.py:6456] Graph capturing finished in 13 secs, took 0.82 GiB
(EngineCore pid=86957) INFO 07-07 02:00:35 [gpu_worker.py:619] CUDA graph pool memory: 0.82 GiB (actual), 0.84 GiB (estimated), difference: 0.02 GiB (2.1%).
(EngineCore pid=86957) INFO 07-07 02:00:35 [jit_monitor.py:54] Kernel JIT monitor activated — Triton JIT compilations during inference will be logged as warnings.
(EngineCore pid=86957) INFO 07-07 02:00:35 [core.py:302] init engine (profile, create kv cache, warmup model) took 29.53 s (compilation: 10.41 s)
(EngineCore pid=86957) INFO 07-07 02:00:36 [kernel.py:270] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

Rendering prompts: 100%|██████████| 35/35 [00:00<00:00, 385.89it/s]

(EngineCore pid=86957) WARNING 07-07 02:00:36 [jit_monitor.py:103] Triton kernel JIT compilation during inference: _compute_slot_mapping_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.
(EngineCore pid=86957) WARNING 07-07 02:00:36 [jit_monitor.py:103] Triton kernel JIT compilation during inference: kernel_unified_attention. This causes a latency spike; consider extending warmup to cover this shape/config.

Processed prompts: 100%|██████████| 35/35 [05:59<00:00, 10.27s/it, est. speed input: 76.45 toks/s, output: 178.65 toks/s]

In [45]:
llm_exclusion_results.head()

  patient_id     trial_id  llm_exclusion_criteria_pass
0      11609  NCT05785741                        False
1      11609  NCT05538130                         True
2      11609  NCT06234423                        False
3      12019  NCT05608252                         True
4      12019  NCT05538130                         True

## 7. Save final matches

Create one review table with one row per patient/trial pair. Each pair is represented by its top-scoring clinical space, rows are ranked by that top match-quality score, and exclusion-check results are included as labels without filtering rows.

In [48]:
patient_context_cols = [
    col
    for col in [
        "patient_id",
        "cancer_history_summary",
        "general_exclusion_criteria_evidence",
    ]
    if col in patient_summaries.columns
]
trial_context_cols = [
    col
    for col in [
        "space_trial_id",
        "clinical_space_number",
        "clinical_space_summary",
        "general_exclusion_criteria",
    ]
    if col in trial_results.columns
]
original_trial_cols = [
    col
    for col in [
        "trial_id",
        "oncore_id",
        "trial_title",
        "brief_summary",
        "detailed_summary",
        "eligibility_criteria",
    ]
    if col in trials.columns
]

final_matches = (
    match_quality_matches.merge(
        candidate_matches[["patient_id", "space_trial_id", "similarity_score", "rank"]],
        on=["patient_id", "space_trial_id"],
        how="left",
    )
    .merge(
        exclusion_results,
        on=["patient_id", "trial_id"],
        how="left",
    )
    .merge(
        patient_summaries[patient_context_cols],
        on="patient_id",
        how="left",
    )
    .merge(
        trial_results[trial_context_cols].drop_duplicates("space_trial_id"),
        on="space_trial_id",
        how="left",
    )
    .merge(
        trials[original_trial_cols].drop_duplicates("trial_id"),
        on="trial_id",
        how="left",
    )
)

# Keep one row per patient/trial pair, represented by the top-scoring clinical space.
final_matches = (
    final_matches.sort_values(
        ["patient_id", "trial_id", "match_quality_score"],
        ascending=[True, True, False],
    )
    .drop_duplicates(["patient_id", "trial_id"], keep="first")
    .sort_values(["patient_id", "match_quality_score"], ascending=[True, False])
    .reset_index(drop=True)
)
final_matches["match_quality_rank"] = final_matches.groupby("patient_id").cumcount() + 1

final_matches = final_matches.rename(
    columns={
        "match_quality_rank": "match_rank",
        "exclusion_criteria_pass": "passes_exclusion_criteria",
        "cancer_history_summary": "patient_summary",
        "general_exclusion_criteria_evidence": "patient_exclusion_evidence",
        "brief_summary": "trial_brief_summary",
        "detailed_summary": "trial_detailed_summary",
        "eligibility_criteria": "trial_eligibility_criteria",
        "clinical_space_summary": "matched_clinical_space_summary",
        "general_exclusion_criteria": "extracted_trial_exclusion_criteria",
    }
)

ordered_cols = [
    "patient_id",
    "trial_id",
    "match_rank",
    "passes_exclusion_criteria",
    "patient_summary",
    "patient_exclusion_evidence",
    "trial_title",
    "trial_brief_summary",
    "trial_eligibility_criteria",
    "clinical_space_number",
    "matched_clinical_space_summary",
    "extracted_trial_exclusion_criteria",
]
final_matches = final_matches[[col for col in ordered_cols if col in final_matches.columns]]
final_matches.head()

,patient_id,trial_id,match_rank,passes_exclusion_criteria,patient_summary,patient_exclusion_evidence,trial_title,trial_brief_summary,trial_eligibility_criteria,clinical_space_number,matched_clinical_space_summary,extracted_trial_exclusion_criteria
0,11609,NCT05785741,1,False,Age: 71\nSex: Female\nCancer type: Glioblastom...,ECOG 4. Essential hypertension. Hyperlipidemia...,"A Phase 1/2a, Multicenter, Open-Label, First i...",This is a dose-escalation and dose-expansion P...,Inclusion Criteria:\n\n1. Male or female adult...,1,Age range allowed: 18 years or older. Sex allo...,Poor performance status (eg ECOG >1).\nLeft ve...
1,11609,NCT05538130,2,True,Age: 71\nSex: Female\nCancer type: Glioblastom...,ECOG 4. Essential hypertension. Hyperlipidemia...,A PHASE 1A/B OPEN-LABEL MASTER STUDY OF PF-077...,The purpose of this clinical trial is to learn...,Inclusion Criteria:\n\n* Diagnosis of advanced...,1,Age range allowed: NA. Sex allowed: Both. Canc...,Brain metastasis larger than 4 cm\nHistory or ...
2,11609,NCT06234423,3,False,Age: 71\nSex: Female\nCancer type: Glioblastom...,ECOG 4. Essential hypertension. Hyperlipidemia...,"A Phase 1, First-in-Human Study of CUSP06, a C...","This phase 1 study will evaluate the safety, t...",Inclusion Criteria:\n\n* Written informed cons...,2,Age range allowed: >=18 years. Sex allowed: Ma...,Poor performance status (ECOG > 1).\nActive or...
3,12019,NCT05608252,1,True,Age: 52\nSex: Female\nCancer type: Breast canc...,"Hypertension, hyperlipidemia, Grade 2 ribocicl...",A Single Arm Phase 1/2 Trial of Abemaciclib + ...,This research is being done to evaluate the sa...,Inclusion Criteria:\n\n* Participants must hav...,1,Age range allowed: >18 years. Sex allowed: Mal...,Poor performance status (ECOG >= 2).\nActive b...
4,12019,NCT05785741,2,True,Age: 52\nSex: Female\nCancer type: Breast canc...,"Hypertension, hyperlipidemia, Grade 2 ribocicl...","A Phase 1/2a, Multicenter, Open-Label, First i...",This is a dose-escalation and dose-expansion P...,Inclusion Criteria:\n\n1. Male or female adult...,1,Age range allowed: 18 years or older. Sex allo...,Poor performance status (eg ECOG >1).\nLeft ve...

In [49]:
# Optional local export for review or downstream analysis.
final_matches.to_csv("output/final_matches.csv", index=None)